# Generated by Django 3.2.3 on 2021-06-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0002_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='descritpion',
            field=models.CharField(default='ABOUT', max_length=264, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, default='FULL NAME', max_length=264),
        ),
    ]
